/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/XzYTzNSWytN
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Baskerville } from 'next/font/google'

libre_baskerville({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card } from "@/components/ui/card"
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"
import { useState } from 'react';
import axios from 'axios';
import React, { useEffect } from 'react';

interface DataItem {
  id: number;
  typeId1: number;
  name: string;
  picThumb: string;
}

interface ApiResponse {
  code: number;
  data: DataItem[];
  msg: string;
}


export function Index() {
  const [animeData, setAnimeData] = useState<DataItem[]>([]);

  useEffect(() => {
    async function fetchData() {
      try {
        const response = await axios.get<ApiResponse>('/api/anime');
        if (response.data.code === 200) {
          setAnimeData(response.data.data);
        }
      } catch (error) {
        console.error("Error fetching data:", error);
      }
    }

    fetchData();
  }, []);
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-gray-950 text-gray-50 px-4 md:px-6 py-3 flex items-center justify-between">
        <Link className="flex items-center gap-2 font-bold text-lg" href="#">
          <FanIcon className="w-6 h-6" />
          <span>Anime Hub</span>
        </Link>
        <nav className="hidden md:flex items-center gap-6">
          <Link className="hover:underline" href="#">
            Browse
          </Link>
          <Link className="hover:underline" href="#">
            Search
          </Link>
          <Link className="hover:underline" href="#">
            Subscriptions
          </Link>
          <Button className="text-gray-50 hover:bg-gray-900/50" variant="ghost">
            Sign In
          </Button>
          <Button className="bg-[#ff6b6b] text-white hover:bg-[#ff4d4d]" variant="outline">
            Sign Up
          </Button>
        </nav>
        <Button className="md:hidden" size="icon" variant="ghost">
          <MenuIcon className="w-6 h-6" />
          <span className="sr-only">Toggle menu</span>
        </Button>
      </header>
      <main className="flex-1">
        <section
            className="bg-gray-950 text-gray-50 py-12 md:py-24 px-4 md:px-6 flex flex-col items-center justify-center">
          <h1 className="text-4xl md:text-6xl font-bold tracking-tighter">Welcome to Anime Hub</h1>
          <p className="text-lg md:text-xl mt-4 max-w-2xl text-center">
            Discover the latest and greatest anime series, movies, and more.
          </p>
          <form className="mt-8 w-full max-w-xl">
            <div className="relative">
              <SearchIcon className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400"/>
              <Input
                  className="bg-gray-900 border-gray-800 text-gray-50 pl-12 pr-4 py-3 rounded-full w-full focus:outline-none focus:ring-2 focus:ring-gray-700"
                  placeholder="Search for anime..."
                  type="search"
              />
            </div>
          </form>
        </section>
        <section className="py-12 md:py-24 px-4 md:px-6">
          <div className="flex items-center justify-between mb-8">
            <h2 className="text-2xl md:text-3xl font-bold">Featured Anime</h2>
            <Link className="text-sm md:text-base hover:underline" href="#">
              View all
            </Link>
          </div>
          <Carousel className="w-full max-w-6xl">
            <CarouselContent>
              {animeData.map((anime) => (
                  <CarouselItem key={anime.id}>
                    <div className="p-2">
                      <Card className="group">
                        <Link href="#">
                          <img
                              alt={`https://www.olevod.tv/player/vod/${anime.typeId1}-${anime.id}-1.html`}
                              className="rounded-lg object-cover w-full aspect-[2/3] group-hover:opacity-80 transition-opacity"
                              height="300"
                              src="/placeholder.svg"
                              width="200"
                          />
                          <div className="mt-4">
                            <h3 className="text-lg font-bold">{anime.name}</h3>
                            <p className="text-gray-400 text-sm">Action, Drama, Fantasy</p>
                          </div>
                        </Link>
                      </Card>
                    </div>
                  </CarouselItem>
              ))}
            </CarouselContent>
            <CarouselPrevious/>
            <CarouselNext/>
          </Carousel>
        </section>
        <section className="py-12 md:py-24 px-4 md:px-6">
          <div className="flex items-center justify-between mb-8">
            <h2 className="text-2xl md:text-3xl font-bold">Trending Anime</h2>
            <Link className="text-sm md:text-base hover:underline" href="#">
              View all
            </Link>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
            <Card className="group">
              <Link href="#">
                <img
                    alt="Chainsaw Man"
                    className="rounded-lg object-cover w-full aspect-[2/3] group-hover:opacity-80 transition-opacity"
                    height="300"
                    src="/placeholder.svg"
                    width="200"
                />
                <div className="mt-4">
                  <h3 className="text-lg font-bold">Chainsaw Man</h3>
                  <p className="text-gray-400 text-sm">Action, Supernatural</p>
                </div>
              </Link>
            </Card>
            <Card className="group">
              <Link href="#">
                <img
                    alt="Spy x Family"
                    className="rounded-lg object-cover w-full aspect-[2/3] group-hover:opacity-80 transition-opacity"
                    height="300"
                    src="/placeholder.svg"
                    width="200"
                />
                <div className="mt-4">
                  <h3 className="text-lg font-bold">Spy x Family</h3>
                  <p className="text-gray-400 text-sm">Action, Comedy</p>
                </div>
              </Link>
            </Card>
            <Card className="group">
              <Link href="#">
                <img
                    alt="Jujutsu Kaisen"
                    className="rounded-lg object-cover w-full aspect-[2/3] group-hover:opacity-80 transition-opacity"
                    height="300"
                    src="/placeholder.svg"
                    width="200"
                />
                <div className="mt-4">
                  <h3 className="text-lg font-bold">Jujutsu Kaisen</h3>
                  <p className="text-gray-400 text-sm">Action, Supernatural</p>
                </div>
              </Link>
            </Card>
            <Card className="group">
              <Link href="#">
                <img
                    alt="Tokyo Revengers"
                    className="rounded-lg object-cover w-full aspect-[2/3] group-hover:opacity-80 transition-opacity"
                    height="300"
                    src="/placeholder.svg"
                    width="200"
                />
                <div className="mt-4">
                  <h3 className="text-lg font-bold">Tokyo Revengers</h3>
                  <p className="text-gray-400 text-sm">Action, Drama</p>
                </div>
              </Link>
            </Card>
          </div>
        </section>
        <section className="py-12 md:py-24 px-4 md:px-6">
          <div className="flex items-center justify-between mb-8">
            <h2 className="text-2xl md:text-3xl font-bold">Recently Added</h2>
            <Link className="text-sm md:text-base hover:underline" href="#">
              View all
            </Link>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
            <Card className="group">
              <Link href="#">
                <img
                    alt="Blue Lock"
                    className="rounded-lg object-cover w-full aspect-[2/3] group-hover:opacity-80 transition-opacity"
                    height="300"
                    src="/placeholder.svg"
                    width="200"
                />
                <div className="mt-4">
                  <h3 className="text-lg font-bold">Blue Lock</h3>
                  <p className="text-gray-400 text-sm">Sports, Drama</p>
                </div>
              </Link>
            </Card>
            <Card className="group">
              <Link href="#">
                <img
                    alt="The Eminence in Shadow"
                    className="rounded-lg object-cover w-full aspect-[2/3] group-hover:opacity-80 transition-opacity"
                    height="300"
                    src="/placeholder.svg"
                    width="200"
                />
                <div className="mt-4">
                  <h3 className="text-lg font-bold">The Eminence in Shadow</h3>
                  <p className="text-gray-400 text-sm">Action, Comedy</p>
                </div>
              </Link>
            </Card>
            <Card className="group">
              <Link href="#">
                <img
                    alt="Mob Psycho 100"
                    className="rounded-lg object-cover w-full aspect-[2/3] group-hover:opacity-80 transition-opacity"
                    height="300"
                    src="/placeholder.svg"
                    width="200"
                />
                <div className="mt-4">
                  <h3 className="text-lg font-bold">Mob Psycho 100</h3>
                  <p className="text-gray-400 text-sm">Action, Comedy, Supernatural</p>
                </div>
              </Link>
            </Card>
            <Card className="group">
              <Link href="#">
                <img
                    alt="Bleach: Thousand-Year Blood War"
                    className="rounded-lg object-cover w-full aspect-[2/3] group-hover:opacity-80 transition-opacity"
                    height="300"
                    src="/placeholder.svg"
                    width="200"
                />
                <div className="mt-4">
                  <h3 className="text-lg font-bold">Bleach: Thousand-Year Blood War</h3>
                  <p className="text-gray-400 text-sm">Action, Supernatural</p>
                </div>
              </Link>
            </Card>
          </div>
        </section>
        <section className="py-12 md:py-24 px-4 md:px-6">
          <div className="flex items-center justify-between mb-8">
            <h2 className="text-2xl md:text-3xl font-bold">Anime Recommendations</h2>
            <Link className="text-sm md:text-base hover:underline" href="#">
              View all
            </Link>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
            <Card className="group">
              <Link href="#">
                <img
                    alt="One Piece"
                    className="rounded-lg object-cover w-full aspect-[2/3] group-hover:opacity-80 transition-opacity"
                    height="300"
                    src="/placeholder.svg"
                    width="200"
                />
                <div className="mt-4">
                  <h3 className="text-lg font-bold">One Piece</h3>
                  <p className="text-gray-400 text-sm">Action, Adventure, Fantasy</p>
                </div>
              </Link>
            </Card>
            <Card className="group">
              <Link href="#">
                <img
                    alt="Naruto"
                    className="rounded-lg object-cover w-full aspect-[2/3] group-hover:opacity-80 transition-opacity"
                    height="300"
                    src="/placeholder.svg"
                    width="200"
                />
                <div className="mt-4">
                  <h3 className="text-lg font-bold">Naruto</h3>
                  <p className="text-gray-400 text-sm">Action, Adventure, Martial Arts</p>
                </div>
              </Link>
            </Card>
            <Card className="group">
              <Link href="#">
                <img
                    alt="Dragon Ball Z"
                    className="rounded-lg object-cover w-full aspect-[2/3] group-hover:opacity-80 transition-opacity"
                    height="300"
                    src="/placeholder.svg"
                    width="200"
                />
                <div className="mt-4">
                  <h3 className="text-lg font-bold">Dragon Ball Z</h3>
                  <p className="text-gray-400 text-sm">Action, Adventure, Fantasy</p>
                </div>
              </Link>
            </Card>
            <Card className="group">
              <Link href="#"/>
            </Card>
          </div>
        </section>
      </main>
    </div>
  )
}

function FanIcon(props) {
  return (
      <svg
          {...props}
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
      >
        <path
            d="M10.827 16.379a6.082 6.082 0 0 1-8.618-7.002l5.412 1.45a6.082 6.082 0 0 1 7.002-8.618l-1.45 5.412a6.082 6.082 0 0 1 8.618 7.002l-5.412-1.45a6.082 6.082 0 0 1-7.002 8.618l1.45-5.412Z"/>
        <path d="M12 12v.01"/>
      </svg>
  )
}


function MenuIcon(props) {
  return (
      <svg
          {...props}
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
      >
        <line x1="4" x2="20" y1="12" y2="12"/>
        <line x1="4" x2="20" y1="6" y2="6"/>
        <line x1="4" x2="20" y1="18" y2="18"/>
      </svg>
  )
}


function SearchIcon(props) {
  return (
      <svg
          {...props}
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
      >
        <circle cx="11" cy="11" r="8"/>
        <path d="m21 21-4.3-4.3"/>
      </svg>
  )
}
